version: "3.7"

services:
    ramses-db:
        image: postgres:14.2
        container_name: ramses-db
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_PASSWORD=${DB_PASSWORD-test}
            - POSTGRES_USER=${DB_USER-test}
            - POSTGRES_DB=${DB_NAME-ramses}
        ports:
            - "5434:5432"
        volumes:
            - "db_data:/var/lib/postgresql/data:rw"
            - "./dump.sql:/dump.sql"
  

    # ramses-api:
    #     build:
    #         dockerfile: ../backend/Dockerfile.backend
    #         context: ../backend
    #     image: local/ramses-api
    #     container_name: ramses-api
    #     env_file:
    #         - .env
    #     tty: true
    #     volumes:
    #         - ../backend:/app/backend/
    #     ports:
    #         - "8000:8000"
    #     command: uvicorn app.main:app --reload --reload-dir "./app/" --workers 1 --host 0.0.0.0 --port 8000
    #     restart: unless-stopped
    #     depends_on:
    #         - ramses-db

volumes:
    db_data:
