"""automigrations

Revision ID: 21c0ea38ab54
Revises: 633874a5211e
Create Date: 2023-01-29 13:20:26.780344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21c0ea38ab54'
down_revision = '633874a5211e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_model_instrument',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('parameter', sa.Float(), nullable=False),
    sa.Column('instrument_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('model_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['trading_model.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('trading_model', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.alter_column('trading_model', 'portfolio_id',
               existing_type=postgresql.UUID(),
               nullable=True)
    op.drop_constraint('trading_model_is_in_production_key', 'trading_model', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('trading_model_is_in_production_key', 'trading_model', ['is_in_production'])
    op.alter_column('trading_model', 'portfolio_id',
               existing_type=postgresql.UUID(),
               nullable=False)
    op.drop_column('trading_model', 'is_active')
    op.drop_table('trading_model_instrument')
    # ### end Alembic commands ###
