"""automigrations

Revision ID: 633874a5211e
Revises: 8ee3d9a0c2a8
Create Date: 2023-01-27 09:04:44.140211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '633874a5211e'
down_revision = '8ee3d9a0c2a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hourly_price_timeseries', 'date_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hourly_price_timeseries', sa.Column('date_2', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
